### ISSUE TITLE
[request] Possibility of mouse emulation like the Android TV version

### ISSUE THREAD

**Issue by nicolas-albert** [JanTrueno/Moonlight-Embedded-Launcher#2]
Hi,
This version work well. I edited the `resolutionOptions` to add `800x600` to respect the 4/3 ratio of the RG35XX-H because with `640x480` games won't launch.

I use a little keyboard/mouse usb device to the OTG port for it's mouse to launch games with Lutris (no gamepad control).

It could be nice to enable a mouse control, like Moonligh Android TV.
This is a toggle mode by pressing the menu (XBox button) button 2 sec, then the left stick can move the mouse and click using buttons.
I think the guide/function button of RG35XX-H can be a good button for this toggle mode.

I tried with `AntiMicroX` on the computer but it's not really good.

Maybe this isn't in the launcher code but directly in the Moonlight code ?

Thx!

**Comment by JanTrueno** [comment]
Hi nicolas, thanks for the feedback :) Happy to hear you like the launcher. Unfortunately mouse mode is not properly implemented in Moonlight-Embedded. You could actually start an issue there in my opinion as you are definitely not the first person to ask for this feature. And its implemented in all other versions of moonlight.

**Comment by JanTrueno** [comment]
There are 3rd party tools you could use for now like: Gopher360, XPadder or Joy2Key

**Comment by nicolas-albert** [comment]
The issue was closed 3 years ago and the code is still here but I failed to toggle this mode by pressing `start` for `750 ms` (that what I understood in the code).
https://github.com/moonlight-stream/moonlight-embedded/issues/724
Any idea ?

**Comment by JanTrueno** [comment]
Yeah this is the semi-implemented mouse-mode. Its not supported on the SDL backend. I'm going to have to fork moonlight and do it myself. Not a huge priority for me tbh.
